export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/.dotfiles/
ZSH_THEME="xxf"
ZSH_CUSTOM=$HOME/.zsh-custom
plugins=(fasd git)
source $ZSH_CUSTOM/lazy-load.sh

group_lazy_load $HOME/.rvm/scripts/rvm
export NVM_DIR=~/.nvm
group_lazy_load $HOME/.nvm/nvm.sh nvm node npm
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/aliases.zsh
source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
