- name: Collecting Facts
  hosts: local
  gather_facts: no

- name: Set up local development environment
  hosts: local
  roles:
    - git
    - vim
    - tmux
    - zsh
    - {role: osx, when: ansible_os_family == "Darwin"}
