#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "Hack Nerd Font:h23"
    filetree_direction = "left"
    filemanager = "defx"
    # Dracula's custom color palette for statusline
    custom_color_palette = [
      ['#44475A', '#8BE9FD', 117, 239],
      ['#6272A4', '#343746', 237, 61],
      ['#6272A4', '#343746', 237, 61],
      ['#343746', 237],
      ['#F8F8F2', '#BD93F9', 255, 141],
      ['#F8F8F2', '#50FA7B', 255, 84],
      ['#F8F8F2', '#FF5555', 255, 203],
    ]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#sh"

[[layers]]
name = "format"

[[layers]]
name = "colorscheme"

[[layers]]
name = "fzf"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
name = "github"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#graphql"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#typescript"

[[custom_plugins]]
repo = "dracula/vim"
name = "dracula"
merged = false
