- name: Adds Telegram repo
  apt_repository:
    repo: 'ppa:atareao/telegram'
    update_cache: yes
  become: true

- name: Install Telegram with apt
  apt: name=telegram state=latest
  become: true

- name: Symlink for Telegram
  file:
    src: /opt/telegram/Telegram
    dest: /usr/bin/telegram
    state: link
