set encoding=utf-8
scriptencoding utf-8
set noshowmode
set t_Co=256
set langmenu=en_US.UTF-8
let $LANG = 'en_US.UTF-8'
set nocompatible
set ttyfast
set lazyredraw
set autoindent
set ignorecase
set relativenumber
set cursorline
set undofile
set undodir=${HOME}/.vimundo/
set hidden
set colorcolumn=100
set termguicolors
set completeopt-=preview
let $NVIM_TUI_ENABLE_TRUE_COLOR=1

" Set leader
let mapleader = "\<Space>"
" Double Leader key moves back to previous file
nnoremap <Leader><Leader> <c-^>
" Leader + d = delete buffer
nnoremap <Leader>d :Bdelete<CR>
" Improving Esc
nnoremap <esc> :noh<return>:set nopaste<return><esc>
" Leader + a to previous buffer
nnoremap <Leader>a :bprevious<CR>
" Leader + s to next buffer
nnoremap <Leader>s :bnext<CR>
" Disabling Ex mode to spot entering in it accidentally
map q: <Nop>
nnoremap Q <nop>

" Show command
set showcmd

" set mouse
if has('mouse') | set mouse=a | endif

" Synchronizes with the system clipboard
set clipboard^=unnamed,unnamedplus
let g:clipboard = {
  \ 'name': 'pbcopy',
  \ 'copy': {
  \    '+': 'pbcopy',
  \    '*': 'pbcopy',
  \  },
  \ 'paste': {
  \    '+': 'pbpaste',
  \    '*': 'pbpaste',
  \ },
  \ 'cache_enabled': 0,
  \ }

" Show number and ruler
set nu
set ruler

" Start searching when you type the first character of the search string
set incsearch
" Any search highlights the string matched by the search
set hlsearch

" Text, tab and ident related
"set smarttab
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab

set ai "Auto ident

" Set font
set guifont=Source_Code_Pro_Medium:h16
let g:Powerline_symbols = 'fancy'

" Smart way to move between windows
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

xnoremap p "_dP


" Turn of backup since there is version controls
set nobackup
set nowb
set noswapfile

" Ignore files
" Useful for ctrlP
set wildignore+=*/assets/*,*/node_modules/*,*/test_out/*,*.so,*.swp,*.zip
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " Linux/MacOSX

source ~/.dotfiles/vim/airline.vim
source ~/.dotfiles/vim/fzf.vim
source ~/.dotfiles/vim/go.vim
source ~/.dotfiles/vim/neoformat.vim
source ~/.dotfiles/vim/nerdtree.vim
source ~/.dotfiles/vim/rg.vim
source ~/.dotfiles/vim/tagbar.vim
source ~/.dotfiles/vim/tmuxline.vim
source ~/.dotfiles/vim/vim-json.vim
source ~/.dotfiles/vim/identline.vim
source ~/.dotfiles/vim/plugins.vim
source ~/.dotfiles/vim/config.vim

autocmd FileType help,nerdtree IndentLinesToggle " Identline brokes identation for Nerdtree and help. This command fixes it.

augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END
