- name: Adds Neovim repo
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'
    update_cache: yes
  become: true

- name: Install Neovim with apt
  apt: name=neovim state=latest
  become: true

- name: Install Vim with apt
  apt: name=vim state=latest
  become: true
