- name: Makes sure autoload directory exists for Neovim
  file:
    path: "{{dotfiles_user_home}}/.config/nvim/autoload"
    state: directory

- name: Install vim-plug for Neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{dotfiles_user_home}}/.config/nvim/autoload/plug.vim"

#- name: Install vim-plug for Vim
  #get_url:
    #url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    #dest: "{{dotfiles_user_home}}/.vim/autoload/plug.vim"

- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink files for Neovim
  file:
    src: "{{dotfiles_home}}/roles/vim/files/{{ item.src }}"
    dest: "{{dotfiles_user_home}}/.config/nvim/{{ item.dest }}"
    state: link
  with_items:
    - src: 'vimrc'
      dest: 'init.vim'
    - src: 'colors'
      dest: 'colors'

- name: Install plugins for Neovim
  command: nvim +PlugInstall +qall
  when: vim_install_plugins
