- import_tasks: osx.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Makes sure autoload directory exists for Neovim
  file:
    path: "{{dotfiles_user_home}}/.config/nvim/autoload"
    state: directory

- name: Install vim-plug for Neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{dotfiles_user_home}}/.config/nvim/autoload/plug.vim"

- name: Copying files for Neovim
  copy:
    src: "{{dotfiles_home}}/roles/vim/files/{{ item.src }}"
    dest: "{{dotfiles_user_home}}/.config/nvim/{{ item.dest }}"
    backup: yes
  with_items:
    - src: 'vimrc'
      dest: 'init.vim'
    - src: 'colors'
      dest: ''

- name: Install plugins for Neovim
  command: nvim +PlugInstall +qall
  when: vim_install_plugins
