- name: Set system defaults
  script: set-defaults.sh
  changed_when: false

- name: Tap into neovim/neovim
  homebrew_tap: tap=neovim/neovim state=present

- name: Tap into caskroom/cask
  homebrew_tap: tap=caskroom/cask state=present

- name: Tap into caskroom/fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: Tap into caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: Tap into buo/cask-upgrade
  homebrew_tap: tap=buo/cask-upgrade state=present

- name: Install mac-specific homebrew packages
  homebrew: name={{item}} state=latest
  with_items: '{{homebrew_packages}}'

- name: Install Mac apps with homebrew cask
  homebrew_cask: name={{item}} state=present
  with_items: '{{cask_packages}}'

- name: Install Mac-App-Store-only apps with mas
  command: mas install {{item}}
  with_items: '{{osx_mas_packages}}'

- name: Configures Spectacle
  file:
    src: "{{dotfiles_home}}/roles/osx/files/spectacle.json"
    dest: "{{dotfiles_user_home}}/Library/Application Support/Spectacle/Shortcuts.json"
    state: link
